config/routes.rb
Rails.application.routes.draw do
  get "/log_in", to: "sessions#new"
  delete "/log_out", to: "sessions#destroy"
  post "/log_in", to: "sessions#create"
  get "/signup", to: "users#new"
  get "static_pages/home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  resources :users
  resources :account_activations, only: [ :edit ]
  resources :password_resets, only: [ :new, :create, :edit, :update ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [ :edit, :update ]
  before_action :valid_user, only: [ :edit, :update ]
  include SessionsHelper
  def new
  end

  def create
    @user = User.find_by(email: reset_params[:email])
    if @user
      @user.create_password_reset
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset intruction"
      redirect_to root_url
    else
      flash[:danger] = "Email is not found"
      render "new", status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render "edit", status: :unprocessable_entity
    elsif @user.update(user_params)
      reset_session
      log_in @user
      @user.forget
      flash[:success] = "Password has been reset"
      redirect_to @user
    else 
      render "edit", status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def get_user
    @user = User.find_by(email: params[:email])
  end

  def valid_user
      unless @user && @user.activated? && @user.authenticated?(:reset, params[:id])
        redirect_to root_path
      end
  end

  def check_expiration
    @user.password_reset_expired?
    flash[:danger] = "Password reset has expired"
    redirect_to new_password_reset_url
  end

  def reset_params
    params.require(:password_reset).permit(:email)
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<%= provide(:title, "Resert Password")  %>

<h1><%= yield :title %></h1>

<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= render "layouts/error" %>
    <%= form_with(model: @user, url:
    password_reset_path(params[:id])) do |f| %>
      <%= hidden_field_tag :email, @user.email %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-
      control' %>
      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<%= provide(:title, "Password Forget") %>
<h1><%= yield :title %></h1>

<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(url: password_resets_path, scope:
    :password_reset) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>