config/routes.rb
Rails.application.routes.draw do
  get "/log_in", to: "sessions#new"
  delete "/log_out", to: "sessions#destroy"
  post "/log_in", to: "sessions#create"
  get "/signup", to: "users#new"
  get "static_pages/home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  resources :users
  resources :account_activations, only: [ :edit ]
  resources :password_resets, only: [ :new, :create, :edit, :update ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/views/layouts/_error.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "errors") %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do | msg | %>
        <li class="text-danger">
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<% nav = {
  About:  { link: about_url },
  Contact:  { link: contact_url },
  News: { link: "https://news.railstutorial.org/" }
} %>
<footer class="navbar navbar-expand-md navbar-inverse border-top">
  <small class="navbar-brand fw-lighter text-body-tertiary fs-6">
    The <a href"https://www.railstutorial.org/" >Ruby on Rails Tutorial</a> by <a href"https://www.michaelhartl.com/"= >Micheal Hartel</a>
</small>
<nav>
  <ul class="nav navbar-collapse navbar-right gap-3">
    <% nav.each do | key, value | %>
      <li class="nav-item" ><%= link_to key, value[:link] %></li>
  <% end %>
  </ul>
</nav>
</footer>

app/views/layouts/_navbar.html.erb
<% nav = {
  Home:  { link: root_url },
  Help:  { link: help_url },
} %>

<header class="navbar navbar-expand-md navbar-inverse bg-black">
  <div class="container">
    <%= link_to "Sample App", "#", id: "logo", class: "navbar-brand" %>

    <!-- Toggler for mobile -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto gap-3">
        <% nav.each do | key, value | %>
          <li class="nav-item">
            <%= link_to key, value[:link], class: "nav-link text-white" %>
          </li>
        <% end %>

        <% if @current_user %>
          <li class="nav-item">
            <%= link_to "User", users_path, class: "nav-link text-white" %>
          </li>

          <li class="nav-item dropdown">
            <a href="#" id="account" class="nav-link dropdown-toggle text-white" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", @current_user, class: "dropdown-item" %></li>
              <li><%= link_to "Settings", edit_user_path(@current_user), class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Log out", log_out_path, data: { "turbo-method": :delete }, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", log_in_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.min.js" integrity="sha384-G/EV+4j2dNv+tEPo3++6LCgdCROaejBqfUeNjuKAiuXbjrxilcCdDz6ZAVfHWe1Y" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sample App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= render "layouts/shim" %>
  <%= javascript_importmap_tags %>
    </head>

  <body>
    <%= render "layouts/navbar"  %>
    <% flash.each do |message_type, message| %>
    <main class="container">
      <%= content_tag(:div, message, 
                      class: "alert alert-#{message_type}") %>
    <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug params if Rails.env.development? %>
    </main>
  </body>
</html>